// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System;
using System.Linq;
using System.Collections.Generic;

namespace Problem002
{
  class MainClass
  {
    public static void Main()
    {
      List<int> fibs = GenerateFibs(4000000);
      int sum = (SumOfEvenFibs(fibs));
      Console.WriteLine(sum);
    }

    public static List<int> GenerateFibs(int limit)
    {
      var fibs = new List<int>{2,1};
      int fibSum = fibs[0] + fibs[1];
      while (fibSum < limit)
      {
        fibs.Insert(0, fibSum);
        fibSum = fibs[0] + fibs[1];
      }
      return fibs;
    }

    public static int SumOfEvenFibs(List<int> fibArray)
    {
      int sum = fibArray.Where(x => x%2 == 0).Sum();
      return sum;
    }
  }
}